import Head from 'next/head'
import { useState } from 'react'

import users from '../api/users'

export default function Admin() {
  const [me, setMe] = useState()

  const View = async () => {
    const viewMe = await users.view() 
    setMe(me)
  }

  return (
    <div>
      <Head>
        <title>Cars - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <aside>
         <p>Algum conteudo relacionado a um &lt;article&gt;</p>
        </aside>
        <button onClick={View} >a</button>
      </main>
    </div>
  )
}
